// Code generated by "stringer -type=RM_APP_TYPE"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RmUnknownApp-0]
	_ = x[RmMainWindow-1]
	_ = x[RmOtherWindow-2]
	_ = x[RmService-3]
	_ = x[RmExplorer-4]
	_ = x[RmConsole-5]
	_ = x[RmCritical-1000]
}

const (
	_RM_APP_TYPE_name_0 = "RmUnknownAppRmMainWindowRmOtherWindowRmServiceRmExplorerRmConsole"
	_RM_APP_TYPE_name_1 = "RmCritical"
)

var (
	_RM_APP_TYPE_index_0 = [...]uint8{0, 12, 24, 37, 46, 56, 65}
)

func (i RM_APP_TYPE) String() string {
	switch {
	case 0 <= i && i <= 5:
		return _RM_APP_TYPE_name_0[_RM_APP_TYPE_index_0[i]:_RM_APP_TYPE_index_0[i+1]]
	case i == 1000:
		return _RM_APP_TYPE_name_1
	default:
		return "RM_APP_TYPE(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
